source 'https://rubygems.org'

ruby '3.3.3'

# Web framework
gem 'sinatra', '~> 3.0'
gem 'rack', '~> 3.0'
gem 'puma', '~> 6.0'
gem 'rack-cors'

# Database
gem 'sequel', '~> 5.0'
gem 'pg'

# Environment
gem 'dotenv'

# JSON
gem 'json'

# HTTP client
gem 'net-http'

# Development
gem 'rerun', group: :development

# Testing
gem 'rspec', '~> 3.12', group: :test
gem 'rack-test', group: :test

# Code quality
gem 'rubocop', group: :development
gem 'rubocop-rspec', group: :development

